---
#pluginDir: /tmp/plugins
#logLevel: debug

transports:
  - name: socket
    config:
      socketaddr: "127.0.0.1:3060"
      type: tcp
  - name: socket
    config:
      socketaddr: "127.0.0.1:6420"
      type: udp

applications:
  - name: prometheus
    config:
      host: 0.0.0.0
      port: 3000
