---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-ceilometercentral
  failurePolicy: Fail
  name: mceilometercentral.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ceilometercentrals
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-ceilometercompute
  failurePolicy: Fail
  name: mceilometercompute.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ceilometercomputes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-infracompute
  failurePolicy: Fail
  name: minfracompute.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - infracomputes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-telemetry
  failurePolicy: Fail
  name: mtelemetry.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - telemetries
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-ceilometercentral
  failurePolicy: Fail
  name: vceilometercentral.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ceilometercentrals
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-ceilometercompute
  failurePolicy: Fail
  name: vceilometercompute.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ceilometercomputes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-infracompute
  failurePolicy: Fail
  name: vinfracompute.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - infracomputes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-telemetry
  failurePolicy: Fail
  name: vtelemetry.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - telemetries
  sideEffects: None
