# permissions for end users to edit ceilometernotificationagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ceilometernotificationagent-editor-role
rules:
- apiGroups:
  - ceilometer.openstack.org
  resources:
  - ceilometernotificationagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ceilometer.openstack.org
  resources:
  - ceilometernotificationagents/status
  verbs:
  - get
