# permissions for end users to edit ceilometercentralagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ceilometercentralagent-editor-role
rules:
- apiGroups:
  - ceilometer.openstack.org
  resources:
  - ceilometercentralagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ceilometer.openstack.org
  resources:
  - ceilometercentralagents/status
  verbs:
  - get
