---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ceilometer.openstack.org
  resources:
  - ceilometercentralagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ceilometer.openstack.org
  resources:
  - ceilometercentralagents/finalizers
  verbs:
  - update
- apiGroups:
  - ceilometer.openstack.org
  resources:
  - ceilometercentralagents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
