apiVersion: telemetry.openstack.org/v1beta1
kind: Telemetry
metadata:
  name: telemetry
  namespace: openstack
spec:
  description: A telemetry deployment
  rabbitMqClusterName: rabbitmq
  ceilometerCentral:
    description: A ceilometer central deployment
    initImage: quay.io/podified-antelope-centos9/openstack-ceilometer-central:current-podified
    centralImage: quay.io/podified-antelope-centos9/openstack-ceilometer-central:current-podified
    notificationImage: quay.io/podified-antelope-centos9/openstack-ceilometer-notification:current-podified
    sgCoreImage: quay.io/infrawatch/sg-core:latest
  ceilometerCompute:
    description: A ceilometer compute deployment
    initImage: quay.io/tripleomastercentos9/openstack-ceilometer-compute:current-tripleo
    computeImage: quay.io/tripleomastercentos9/openstack-ceilometer-compute:current-tripleo
    playbook: deploy-ceilometer.yaml
