apiVersion: telemetry.openstack.org/v1beta1
kind: Telemetry
metadata:
  name: telemetry
  namespace: openstack
spec:
  ceilometerCentral:
    initImage: quay.io/podified-antelope-centos9/openstack-ceilometer-central:current-podified
    centralImage: quay.io/podified-antelope-centos9/openstack-ceilometer-central:current-podified
    notificationImage: quay.io/podified-antelope-centos9/openstack-ceilometer-notification:current-podified
    sgCoreImage: quay.io/infrawatch/sg-core:latest
    serviceAccount: telemetry-operator-telemetry
  ceilometerCompute:
    initImage: quay.io/podified-antelope-centos9/openstack-ceilometer-compute:current-podified
    computeImage: quay.io/podified-antelope-centos9/openstack-ceilometer-compute:current-podified
    dataplaneSSHSecret: dataplane-ansible-ssh-private-key-secret
    dataplaneInventoryConfigMap: dataplanerole-edpm-compute
    serviceAccount: telemetry-operator-telemetry
  infraCompute:
    nodeExporterImage: quay.io/prometheus/node-exporter:v1.5.0
    serviceAccount: telemetry-operator-telemetry
    dataplaneSSHSecret: dataplane-ansible-ssh-private-key-secret
    dataplaneInventoryConfigMap: dataplanerole-edpm-compute
