apiVersion: telemetry.openstack.org/v1beta1
kind: Telemetry
metadata:
  name: telemetry
spec:
  metricStorage:
    enabled: false
    monitoringStack:
      type: prometheus
      alertingEnabled: true
      scrapeInterval: 30s
      replicas: 1
      storage:
        strategy: persistent
        retention: 24h
        persistent:
          pvcStorageRequest: 20G
  autoscaling:
    enabled: false
    prometheus:
      deployPrometheus: true
    aodh:
      passwordSelectors:
      databaseUser: aodh
      databaseInstance: openstack
      memcachedInstance: memcached
      secret: osp-secret
    heatInstance: heat
  ceilometer:
    enabled: true
    secret: osp-secret
  logging:
    enabled: false
    network: internalapi
    ipaddr: 172.17.0.80
    port: 10514
    cloNamespace: openshift-logging
