apiVersion: telemetry.openstack.org/v1beta1
kind: Telemetry
metadata:
  name: telemetry
spec:
  autoscaling:
    enabled: false
    prometheus:
      deployPrometheus: true
    aodh:
      passwordSelectors:
      databaseUser: aodh
      databaseInstance: openstack
      memcachedInstance: memcached
    heatInstance: heat
  ceilometer:
    enabled: true
  secret: osp-secret
