apiVersion: telemetry.openstack.org/v1beta1
kind: Telemetry
metadata:
  name: telemetry
  namespace: openstack
spec:
  description: A telemetry deployment
  rabbitMqClusterName: rabbitmq
  ceilometerCentral:
    description: A ceilometer central deployment
    initImage: quay.io/podified-antelope-centos9/openstack-ceilometer-central:current-podified
    centralImage: quay.io/podified-antelope-centos9/openstack-ceilometer-central:current-podified
    notificationImage: quay.io/podified-antelope-centos9/openstack-ceilometer-notification:current-podified
    sgCoreImage: quay.io/infrawatch/sg-core:latest
  ceilometerCompute:
    description: A ceilometer compute deployment
    play: |
      - name: Print hello world
        hosts: all
        tasks:
          - name: Using debug statement
            ansible.builtin.debug:
              msg: "Hello, world this is ceilometer-ansibleee.yaml"
    inventory: |
      Compute:
        hosts:
          compute-0:
            ansible_host: 192.168.122.197
        vars:
          ansible_ssh_user: root
      allovercloud:
        children:
          Compute:
      overcloud:
        children:
          Compute:
