---
- hosts: all
  ignore_errors: true
  tasks:
    #- name: Get list of zuul projects
    #  debug:
    #    msg: "{{ zuul.projects }}"
    #
    #- name: Get projects/telemetry-tempest-plugin
    #  ansible.builtin.debug:
    #    msg: "{{ zuul.projects['opendev.org/openstack/telemetry-tempest-plugin'] }}"
    #
    #- name: Get zuul/items
    #  ansible.builtin.debug:
    #    var: zuul.items
    #
    #- name: Get projects/telemetry-tempest-plugin
    #  ansible.builtin.debug:
    #    var: zuul.projects['opendev.org/openstack/telemetry-tempest-plugin']
    #
    #- name: Get zuul/items
    #  ansible.builtin.debug:
    #    var: zuul.items
    #
    #- name: Get the FETCH_HEAD from git
    #  shell: |
    #    cat {{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/telemetry-tempest-plugin'].src_dir }}/.git/FETCH_HEAD
    #
    #- name: Get FETCH_HEAD (lookup)
    #  debug:
    #    msg: "{{  ansible.builtin.lookup('file', [ ansible_user_dir, zuul.projects['opendev.org/openstack/telemetry-tempest-plugin'].src_dir, '.git/FETCH_HEAD' ] | join('/')) }}"

    - name: show external plugin config
      debug:
        msg: "{{ cifmw_test_operator_tempest_external_plugin }}"
